import type { Language } from '@/types';

export type LegalBlock =
  | { t: 'p'; text: string }
  | { t: 'h2'; text: string }
  | { t: 'ul'; items: string[] }
  | { t: 'table'; head: string[]; rows: string[][] };

export interface LegalDoc {
  title: string;
  effectiveDate: string;
  blocks: LegalBlock[];
}

const EMAIL = 'contact@ai-issue.com';

export const PRIVACY: Record<Language, LegalDoc> = {
  ja: {
    title: 'プライバシーポリシー',
    effectiveDate: '施行日: 2026年6月14日',
    blocks: [
      { t: 'p', text: 'AI issue（以下「本サービス」）は、利用者の個人情報を大切に取り扱い、関連法令を遵守します。' },
      { t: 'h2', text: '1. 収集する個人情報の項目' },
      { t: 'p', text: '本サービスはニュースレター購読のお申し込み時に以下の項目を収集します。' },
      { t: 'ul', items: ['メールアドレス'] },
      { t: 'p', text: '会員登録なしでご利用いただけ、それ以外の個人情報は収集しません。' },
      { t: 'h2', text: '2. 個人情報の収集目的' },
      { t: 'p', text: '収集したメールアドレスは次の目的にのみ使用します。' },
      { t: 'ul', items: ['AIニュース・ツール情報のニュースレター配信'] },
      { t: 'h2', text: '3. 個人情報の保有および利用期間' },
      { t: 'p', text: '配信停止のお申し出があり次第、速やかに削除します。ニュースレター下部の「配信停止」リンクからいつでも解除できます。' },
      { t: 'h2', text: '4. 個人情報の第三者提供' },
      { t: 'p', text: '収集した個人情報は原則として第三者に提供しません。ただし、メール配信のため以下のサービスを利用します。' },
      { t: 'table', head: ['委託先', '委託業務', '保有期間'], rows: [['Resend Inc.', 'メール配信', '配信停止まで']] },
      { t: 'h2', text: '5. 利用者の権利' },
      { t: 'p', text: '利用者はいつでも以下の権利を行使できます。' },
      { t: 'ul', items: ['個人情報の開示請求', '個人情報の削除請求（配信停止）', '個人情報の処理停止請求'] },
      { t: 'p', text: 'お問い合わせは下記の連絡先までお願いいたします。' },
      { t: 'h2', text: '6. クッキーの使用' },
      { t: 'p', text: '本サービスは利用状況の分析のためにクッキーを使用する場合があります。ブラウザの設定でクッキーの保存を拒否できますが、一部の機能がご利用いただけない場合があります。' },
      { t: 'h2', text: '7. 個人情報保護責任者' },
      { t: 'ul', items: ['サービス名: AI issue', `メール: ${EMAIL}`] },
      { t: 'p', text: '個人情報の取り扱いに関するお問い合わせ・苦情・被害救済などは上記メールまでご連絡ください。' },
      { t: 'h2', text: '8. 改定履歴' },
      { t: 'p', text: '本ポリシーは法令またはサービスの変更に応じて改定されることがあり、変更時はサービス内の告知でお知らせします。' },
    ],
  },
  ko: {
    title: '개인정보처리방침',
    effectiveDate: '시행일: 2026년 6월 14일',
    blocks: [
      { t: 'p', text: 'AI issue(이하 "서비스")는 이용자의 개인정보를 소중히 여기며, 「개인정보 보호법」을 준수합니다.' },
      { t: 'h2', text: '1. 수집하는 개인정보 항목' },
      { t: 'p', text: '서비스는 뉴스레터 구독 신청 시 아래 항목을 수집합니다.' },
      { t: 'ul', items: ['이메일 주소'] },
      { t: 'p', text: '별도의 회원가입 없이 이용할 수 있으며, 그 외 개인정보는 수집하지 않습니다.' },
      { t: 'h2', text: '2. 개인정보 수집 목적' },
      { t: 'p', text: '수집한 이메일 주소는 다음 목적으로만 사용됩니다.' },
      { t: 'ul', items: ['AI 뉴스 및 툴 정보 뉴스레터 발송'] },
      { t: 'h2', text: '3. 개인정보 보유 및 이용 기간' },
      { t: 'p', text: '구독 해지 요청 시 즉시 삭제합니다. 뉴스레터 하단의 "구독 해지" 링크를 통해 언제든지 해지할 수 있습니다.' },
      { t: 'h2', text: '4. 개인정보의 제3자 제공' },
      { t: 'p', text: '수집한 개인정보는 원칙적으로 제3자에게 제공하지 않습니다. 다만, 이메일 발송을 위해 아래 서비스를 이용합니다.' },
      { t: 'table', head: ['수탁업체', '위탁 업무', '보유 기간'], rows: [['Resend Inc.', '이메일 발송', '구독 해지 시까지']] },
      { t: 'h2', text: '5. 이용자의 권리' },
      { t: 'p', text: '이용자는 언제든지 아래 권리를 행사할 수 있습니다.' },
      { t: 'ul', items: ['개인정보 열람 요청', '개인정보 삭제 요청 (구독 해지)', '개인정보 처리 정지 요청'] },
      { t: 'p', text: '문의는 아래 연락처로 해주시기 바랍니다.' },
      { t: 'h2', text: '6. 쿠키 사용' },
      { t: 'p', text: '서비스는 사이트 이용 분석을 위해 쿠키를 사용할 수 있습니다. 브라우저 설정을 통해 쿠키 저장을 거부할 수 있으나, 일부 서비스 이용에 제한이 생길 수 있습니다.' },
      { t: 'h2', text: '7. 개인정보 보호책임자' },
      { t: 'ul', items: ['서비스명: AI issue', `이메일: ${EMAIL}`] },
      { t: 'p', text: '개인정보 처리에 관한 문의, 불만, 피해 구제 등은 위 이메일로 연락주시기 바랍니다.' },
      { t: 'h2', text: '8. 개정 이력' },
      { t: 'p', text: '본 방침은 법령 또는 서비스 변경에 따라 개정될 수 있으며, 변경 시 서비스 내 공지를 통해 안내합니다.' },
    ],
  },
  en: {
    title: 'Privacy Policy',
    effectiveDate: 'Effective: June 14, 2026',
    blocks: [
      { t: 'p', text: 'AI issue (the "Service") values your personal information and complies with applicable data protection laws.' },
      { t: 'h2', text: '1. Information We Collect' },
      { t: 'p', text: 'The Service collects the following item when you subscribe to the newsletter.' },
      { t: 'ul', items: ['Email address'] },
      { t: 'p', text: 'You can use the Service without creating an account, and no other personal information is collected.' },
      { t: 'h2', text: '2. Purpose of Collection' },
      { t: 'p', text: 'Your email address is used only for the following purpose.' },
      { t: 'ul', items: ['Delivering the AI news and tools newsletter'] },
      { t: 'h2', text: '3. Retention and Use Period' },
      { t: 'p', text: 'We delete your information promptly upon an unsubscribe request. You can unsubscribe at any time via the "Unsubscribe" link at the bottom of the newsletter.' },
      { t: 'h2', text: '4. Provision to Third Parties' },
      { t: 'p', text: 'In principle, we do not provide your personal information to third parties. However, we use the following service to send emails.' },
      { t: 'table', head: ['Processor', 'Task', 'Retention'], rows: [['Resend Inc.', 'Email delivery', 'Until unsubscribe']] },
      { t: 'h2', text: '5. Your Rights' },
      { t: 'p', text: 'You may exercise the following rights at any time.' },
      { t: 'ul', items: ['Request access to your personal information', 'Request deletion (unsubscribe)', 'Request suspension of processing'] },
      { t: 'p', text: 'For inquiries, please contact us at the address below.' },
      { t: 'h2', text: '6. Cookies' },
      { t: 'p', text: 'The Service may use cookies to analyze site usage. You can refuse cookies in your browser settings, but some features may be limited.' },
      { t: 'h2', text: '7. Data Protection Officer' },
      { t: 'ul', items: ['Service: AI issue', `Email: ${EMAIL}`] },
      { t: 'p', text: 'Please direct any inquiries, complaints, or remediation requests regarding personal information to the email above.' },
      { t: 'h2', text: '8. Revision History' },
      { t: 'p', text: 'This policy may be revised in response to changes in law or the Service, and we will announce any changes within the Service.' },
    ],
  },
};

export const TERMS: Record<Language, LegalDoc> = {
  ja: {
    title: '利用規約',
    effectiveDate: '施行日: 2026年6月14日',
    blocks: [
      { t: 'p', text: '本規約は、AI issue（以下「本サービス」）の利用条件を定めるものです。' },
      { t: 'h2', text: '1. サービスの紹介' },
      { t: 'p', text: 'AI issueは、AI関連のニュースおよび新着ツール情報を自動で収集・要約して提供するキュレーションサービスです。会員登録なしでご利用いただけ、ニュースレターの購読により定期的に情報を受け取れます。' },
      { t: 'h2', text: '2. コンテンツ免責事項' },
      { t: 'p', text: '本サービスが提供するコンテンツは、AIが外部のRSSフィードおよび公開された情報源を自動的に収集・要約したものです。' },
      { t: 'ul', items: ['コンテンツの正確性・完全性・最新性を保証しません。', '運営者はコンテンツの利用により生じた損害について責任を負いません。', '重要な意思決定の際は原文の出典を直接ご確認ください。'] },
      { t: 'h2', text: '3. 著作権' },
      { t: 'ul', items: ['本サービス自体のデザイン・UI・ロゴ等の著作権はAI issueに帰属します。', '収集・要約されたコンテンツの著作権は各原文の出典に帰属し、本サービスは出典を明示します。', 'サービス内コンテンツの無断複製・配布を禁止します。'] },
      { t: 'h2', text: '4. 禁止事項' },
      { t: 'p', text: '利用者は次の行為を行ってはなりません。' },
      { t: 'ul', items: ['サービスを違法な目的で利用する行為', 'サービスの正常な運営を妨害する行為', '他人の個人情報を収集または盗用する行為', 'サービスのコンテンツを無断で商用利用する行為'] },
      { t: 'h2', text: '5. サービスの変更および中断' },
      { t: 'p', text: '本サービスは運営上の必要に応じて内容を変更し、または一時的に中断することがあります。これにより生じた利用者の損害について別途の補償は行いません。' },
      { t: 'h2', text: '6. 規約の変更' },
      { t: 'p', text: '本規約はサービス方針の変更に応じて改定されることがあり、変更時はサービス内の告知でお知らせします。変更後の規約は告知から7日が経過した時点で効力を生じます。' },
      { t: 'h2', text: '7. 準拠法および管轄' },
      { t: 'p', text: '本規約は大韓民国の法律に準拠し、紛争が生じた場合はソウル中央地方法院を第一審の管轄裁判所とします。' },
      { t: 'h2', text: '8. お問い合わせ' },
      { t: 'ul', items: ['サービス名: AI issue', `メール: ${EMAIL}`] },
    ],
  },
  ko: {
    title: '이용약관',
    effectiveDate: '시행일: 2026년 6월 14일',
    blocks: [
      { t: 'p', text: '본 약관은 AI issue(이하 "서비스")의 이용 조건을 규정합니다.' },
      { t: 'h2', text: '1. 서비스 소개' },
      { t: 'p', text: 'AI issue는 인공지능 관련 뉴스 및 신규 툴 정보를 자동으로 수집·요약하여 제공하는 큐레이션 서비스입니다. 별도의 회원가입 없이 이용할 수 있으며, 뉴스레터 구독을 통해 정기적으로 정보를 받아볼 수 있습니다.' },
      { t: 'h2', text: '2. 콘텐츠 면책 조항' },
      { t: 'p', text: '서비스에서 제공하는 콘텐츠는 AI가 외부 RSS 피드 및 공개된 정보 소스를 자동 수집·요약한 것입니다.' },
      { t: 'ul', items: ['콘텐츠의 정확성, 완전성, 최신성을 보장하지 않습니다.', '서비스 운영자는 콘텐츠 이용으로 인해 발생한 손해에 대해 책임을 지지 않습니다.', '중요한 의사결정에는 원문 출처를 직접 확인하시기 바랍니다.'] },
      { t: 'h2', text: '3. 저작권' },
      { t: 'ul', items: ['서비스 자체 디자인, UI, 로고 등의 저작권은 AI issue에 있습니다.', '수집·요약된 콘텐츠의 저작권은 각 원문 출처에 있으며, 서비스는 해당 출처를 명시합니다.', '서비스 내 콘텐츠를 무단으로 복제·배포하는 행위를 금지합니다.'] },
      { t: 'h2', text: '4. 금지 행위' },
      { t: 'p', text: '이용자는 다음 행위를 해서는 안 됩니다.' },
      { t: 'ul', items: ['서비스를 불법적인 목적으로 이용하는 행위', '서비스의 정상적인 운영을 방해하는 행위', '타인의 개인정보를 수집하거나 도용하는 행위', '서비스 콘텐츠를 상업적으로 무단 이용하는 행위'] },
      { t: 'h2', text: '5. 서비스 변경 및 중단' },
      { t: 'p', text: '서비스는 운영상 필요에 따라 내용을 변경하거나 일시적으로 중단할 수 있습니다. 이로 인한 이용자의 손해에 대해 별도의 보상을 제공하지 않습니다.' },
      { t: 'h2', text: '6. 약관 변경' },
      { t: 'p', text: '본 약관은 서비스 정책 변경 시 수정될 수 있으며, 변경 시 서비스 내 공지를 통해 안내합니다. 변경된 약관은 공지 후 7일이 지난 시점부터 효력이 발생합니다.' },
      { t: 'h2', text: '7. 준거법 및 관할' },
      { t: 'p', text: '본 약관은 대한민국 법률에 따르며, 분쟁 발생 시 서울중앙지방법원을 제1심 관할 법원으로 합니다.' },
      { t: 'h2', text: '8. 문의' },
      { t: 'ul', items: ['서비스명: AI issue', `이메일: ${EMAIL}`] },
    ],
  },
  en: {
    title: 'Terms of Service',
    effectiveDate: 'Effective: June 14, 2026',
    blocks: [
      { t: 'p', text: 'These Terms set out the conditions for using AI issue (the "Service").' },
      { t: 'h2', text: '1. About the Service' },
      { t: 'p', text: 'AI issue is a curation service that automatically collects and summarizes AI-related news and new tool information. You can use it without registration and receive regular updates by subscribing to the newsletter.' },
      { t: 'h2', text: '2. Content Disclaimer' },
      { t: 'p', text: 'Content provided by the Service is automatically collected and summarized by AI from external RSS feeds and publicly available sources.' },
      { t: 'ul', items: ['We do not guarantee the accuracy, completeness, or timeliness of the content.', 'The operator is not liable for any damages arising from use of the content.', 'For important decisions, please verify the original sources directly.'] },
      { t: 'h2', text: '3. Copyright' },
      { t: 'ul', items: ['The copyright of the Service’s own design, UI, and logo belongs to AI issue.', 'The copyright of collected and summarized content belongs to each original source, which the Service indicates.', 'Unauthorized reproduction or distribution of content within the Service is prohibited.'] },
      { t: 'h2', text: '4. Prohibited Conduct' },
      { t: 'p', text: 'Users must not engage in the following.' },
      { t: 'ul', items: ['Using the Service for illegal purposes', 'Interfering with the normal operation of the Service', 'Collecting or misusing the personal information of others', 'Using the Service’s content commercially without authorization'] },
      { t: 'h2', text: '5. Changes and Suspension of the Service' },
      { t: 'p', text: 'The Service may change its content or temporarily suspend operation as operationally necessary. No separate compensation will be provided for any resulting damages to users.' },
      { t: 'h2', text: '6. Changes to the Terms' },
      { t: 'p', text: 'These Terms may be revised when service policies change, and changes will be announced within the Service. The revised Terms take effect 7 days after the announcement.' },
      { t: 'h2', text: '7. Governing Law and Jurisdiction' },
      { t: 'p', text: 'These Terms are governed by the laws of the Republic of Korea, and the Seoul Central District Court shall be the court of first instance for any disputes.' },
      { t: 'h2', text: '8. Contact' },
      { t: 'ul', items: ['Service: AI issue', `Email: ${EMAIL}`] },
    ],
  },
};
