import type { Language } from '@/types';

export type LegalBlock =
  | { t: 'p'; text: string }
  | { t: 'h2'; text: string }
  | { t: 'ul'; items: string[] }
  | { t: 'table'; head: string[]; rows: string[][] };

export interface LegalDoc {
  title: string;
  effectiveDate: string;
  blocks: LegalBlock[];
}

export const PRIVACY: Record<Language, LegalDoc> = {
  ja: {
    title: 'プライバシーポリシー',
    effectiveDate: '施行日：2026年6月14日',
    blocks: [
      { t: 'p', text: 'AI issue（以下「本サービス」）は、利用者の個人情報を大切に扱い、関連法令を遵守します。' },
      { t: 'h2', text: '1. 収集する個人情報の項目' },
      { t: 'p', text: '本サービスは、ニュースレターの購読申し込み時に以下の情報を収集します。' },
      { t: 'ul', items: ['メールアドレス'] },
      { t: 'p', text: '会員登録は不要であり、それ以外の個人情報は収集しません。' },
      { t: 'h2', text: '2. 個人情報の収集目的' },
      { t: 'p', text: '収集したメールアドレスは、以下の目的にのみ使用します。' },
      { t: 'ul', items: ['AIニュースおよびツール情報に関するニュースレターの配信'] },
      { t: 'h2', text: '3. 個人情報の保有期間' },
      { t: 'p', text: '購読解除のリクエストがあった場合、速やかに削除します。ニュースレター下部の「購読解除」リンクからいつでも解除できます。' },
      { t: 'h2', text: '4. 第三者への提供' },
      { t: 'p', text: '収集した個人情報は、原則として第三者に提供しません。ただし、メール配信のために以下のサービスを利用しています。' },
      { t: 'table', head: ['委託先', '委託業務', '保有期間'], rows: [['Resend Inc.', 'メール配信', '購読解除まで']] },
      { t: 'h2', text: '5. 利用者の権利' },
      { t: 'p', text: '利用者はいつでも以下の権利を行使できます。' },
      { t: 'ul', items: ['個人情報の開示請求', '個人情報の削除請求（購読解除）', '個人情報の処理停止請求'] },
      { t: 'h2', text: '6. Cookieの使用' },
      { t: 'p', text: '本サービスは、利用状況の分析のためにCookieを使用することがあります。ブラウザの設定からCookieの保存を拒否することができますが、一部のサービスが制限される場合があります。' },
      { t: 'p', text: 'また、本サービスは第三者配信の広告サービス（Google AdSense）を利用しています。Googleを含む第三者は、広告配信のためにCookieを使用し、利用者の本サイトや他サイトへのアクセス情報に基づいて広告を表示する場合があります。パーソナライズ広告は、Googleの広告設定（https://www.google.com/settings/ads）から無効にできます。' },
      { t: 'h2', text: '7. 個人情報管理責任者' },
      { t: 'ul', items: ['サービス名：AI issue', 'メールアドレス：contact@ai-issue.com'] },
      { t: 'h2', text: '8. 改定履歴' },
      { t: 'p', text: '本ポリシーは、法令またはサービスの変更に応じて改定されることがあります。変更がある場合は、本サービス内での告知を通じてお知らせします。' },
    ],
  },
  ko: {
    title: '개인정보처리방침',
    effectiveDate: '시행일: 2026년 6월 14일',
    blocks: [
      { t: 'p', text: 'AI issue(이하 "서비스")는 이용자의 개인정보를 소중히 여기며, 관련 법령을 준수합니다.' },
      { t: 'h2', text: '1. 수집하는 개인정보 항목' },
      { t: 'p', text: '서비스는 뉴스레터 구독 신청 시 아래 항목을 수집합니다.' },
      { t: 'ul', items: ['이메일 주소'] },
      { t: 'p', text: '별도의 회원가입 없이 이용할 수 있으며, 그 외 개인정보는 수집하지 않습니다.' },
      { t: 'h2', text: '2. 개인정보 수집 목적' },
      { t: 'p', text: '수집한 이메일 주소는 다음 목적으로만 사용됩니다.' },
      { t: 'ul', items: ['AI 뉴스 및 툴 정보 뉴스레터 발송'] },
      { t: 'h2', text: '3. 개인정보 보유 및 이용 기간' },
      { t: 'p', text: '구독 해지 요청 시 즉시 삭제합니다. 뉴스레터 하단의 "구독 해지" 링크를 통해 언제든지 해지할 수 있습니다.' },
      { t: 'h2', text: '4. 개인정보의 제3자 제공' },
      { t: 'p', text: '수집한 개인정보는 원칙적으로 제3자에게 제공하지 않습니다. 다만, 이메일 발송을 위해 아래 서비스를 이용합니다.' },
      { t: 'table', head: ['수탁업체', '위탁 업무', '보유 기간'], rows: [['Resend Inc.', '이메일 발송', '구독 해지 시까지']] },
      { t: 'h2', text: '5. 이용자의 권리' },
      { t: 'p', text: '이용자는 언제든지 아래 권리를 행사할 수 있습니다.' },
      { t: 'ul', items: ['개인정보 열람 요청', '개인정보 삭제 요청 (구독 해지)', '개인정보 처리 정지 요청'] },
      { t: 'h2', text: '6. 쿠키 사용' },
      { t: 'p', text: '서비스는 사이트 이용 분석을 위해 쿠키를 사용할 수 있습니다. 브라우저 설정을 통해 쿠키 저장을 거부할 수 있으나, 일부 서비스 이용에 제한이 생길 수 있습니다.' },
      { t: 'p', text: '또한 본 서비스는 제3자 광고 서비스(Google AdSense)를 이용합니다. Google을 포함한 제3자는 광고 게재를 위해 쿠키를 사용하며, 이용자의 본 사이트 및 다른 사이트 방문 정보를 바탕으로 광고를 표시할 수 있습니다. 맞춤 광고는 Google 광고 설정(https://www.google.com/settings/ads)에서 거부할 수 있습니다.' },
      { t: 'h2', text: '7. 개인정보 보호책임자' },
      { t: 'ul', items: ['서비스명: AI issue', '이메일: contact@ai-issue.com'] },
      { t: 'h2', text: '8. 개정 이력' },
      { t: 'p', text: '본 방침은 법령 또는 서비스 변경에 따라 개정될 수 있으며, 변경 시 서비스 내 공지를 통해 안내합니다.' },
    ],
  },
  en: {
    title: 'Privacy Policy',
    effectiveDate: 'Effective Date: June 14, 2026',
    blocks: [
      { t: 'p', text: 'AI issue (the "Service") respects your privacy and is committed to protecting your personal information in accordance with applicable laws.' },
      { t: 'h2', text: '1. Information We Collect' },
      { t: 'p', text: 'We collect the following information when you subscribe to our newsletter:' },
      { t: 'ul', items: ['Email address'] },
      { t: 'p', text: 'No account registration is required to use the Service, and we do not collect any other personal information.' },
      { t: 'h2', text: '2. Purpose of Collection' },
      { t: 'p', text: 'Your email address is used solely for the following purpose:' },
      { t: 'ul', items: ['Sending newsletters about AI news and tool updates'] },
      { t: 'h2', text: '3. Retention Period' },
      { t: 'p', text: 'Your information is deleted promptly upon request to unsubscribe. You may unsubscribe at any time using the "Unsubscribe" link in any newsletter.' },
      { t: 'h2', text: '4. Sharing with Third Parties' },
      { t: 'p', text: 'We do not share your personal information with third parties, except as necessary for email delivery through the following service:' },
      { t: 'table', head: ['Provider', 'Purpose', 'Retention'], rows: [['Resend Inc.', 'Email delivery', 'Until unsubscribe']] },
      { t: 'h2', text: '5. Your Rights' },
      { t: 'p', text: 'You have the right to:' },
      { t: 'ul', items: ['Request access to your personal information', 'Request deletion of your personal information (unsubscribe)', 'Request that we stop processing your information'] },
      { t: 'p', text: 'Depending on your country of residence, you may have additional rights under applicable law (e.g., GDPR for EEA residents, CCPA for California residents).' },
      { t: 'h2', text: '6. Cookies' },
      { t: 'p', text: 'The Service may use cookies to analyze usage patterns. You may disable cookies through your browser settings, though some features of the Service may be affected.' },
      { t: 'p', text: 'The Service also uses a third-party advertising service (Google AdSense). Third parties, including Google, may use cookies to serve ads based on your visits to this and other websites. You can opt out of personalized advertising through Google Ads Settings (https://www.google.com/settings/ads).' },
      { t: 'h2', text: '7. Contact' },
      { t: 'ul', items: ['Service: AI issue', 'Email: contact@ai-issue.com'] },
      { t: 'h2', text: '8. Updates to This Policy' },
      { t: 'p', text: 'This policy may be updated to reflect changes in the law or our practices. We will notify users of any material changes through the Service.' },
    ],
  },
};

export const TERMS: Record<Language, LegalDoc> = {
  ja: {
    title: '利用規約',
    effectiveDate: '施行日：2026年6月14日',
    blocks: [
      { t: 'p', text: '本規約は、AI issue（以下「本サービス」）の利用条件を定めるものです。' },
      { t: 'h2', text: '1. サービスの概要' },
      { t: 'p', text: 'AI issueは、人工知能に関するニュースおよび新しいツール情報を自動的に収集・要約して提供するキュレーションサービスです。会員登録不要でご利用いただけるほか、ニュースレターを購読することで定期的に情報をお受け取りいただけます。' },
      { t: 'h2', text: '2. コンテンツの免責事項' },
      { t: 'p', text: '本サービスで提供するコンテンツは、AIが外部のRSSフィードおよび公開情報ソースを自動収集・要約したものです。' },
      { t: 'ul', items: ['コンテンツの正確性、完全性、最新性を保証するものではありません。', '本サービスの運営者は、コンテンツの利用によって生じた損害について責任を負いません。', '重要な意思決定を行う際は、必ず原文の情報源をご確認ください。'] },
      { t: 'h2', text: '3. 著作権' },
      { t: 'ul', items: ['本サービスのデザイン、UI、ロゴ等の著作権はAI issueに帰属します。', '収集・要約されたコンテンツの著作権は各原文の情報源に帰属し、本サービスは該当する出典を明示します。', '本サービス内のコンテンツを無断で複製・配布する行為を禁止します。'] },
      { t: 'h2', text: '4. 禁止事項' },
      { t: 'p', text: '利用者は以下の行為を行ってはなりません。' },
      { t: 'ul', items: ['本サービスを違法な目的で利用する行為', '本サービスの正常な運営を妨げる行為', '第三者の個人情報を収集または不正に使用する行為', '本サービスのコンテンツを商業目的で無断利用する行為'] },
      { t: 'h2', text: '5. サービスの変更・中断' },
      { t: 'p', text: '本サービスは、運営上の必要に応じて内容を変更し、または一時的に中断することがあります。これにより生じた利用者の損害について、別途補償を行いません。' },
      { t: 'h2', text: '6. 規約の変更' },
      { t: 'p', text: '本規約は、サービスポリシーの変更に伴い修正されることがあります。変更がある場合は、本サービス内での告知を通じてお知らせします。変更後の規約は、告知から7日が経過した時点で効力が生じます。' },
      { t: 'h2', text: '7. 準拠法および紛争解決' },
      { t: 'p', text: '本規約の解釈および適用は、サービス運営者の所在地の法律を準拠法とします。ただし、利用者が所在する国の強行法規がある場合は、当該法規が優先して適用される場合があります。紛争が生じた場合は、相互の協議による解決を原則とします。' },
      { t: 'h2', text: '8. お問い合わせ' },
      { t: 'ul', items: ['サービス名：AI issue', 'メールアドレス：contact@ai-issue.com'] },
    ],
  },
  ko: {
    title: '이용약관',
    effectiveDate: '시행일: 2026년 6월 14일',
    blocks: [
      { t: 'p', text: '본 약관은 AI issue(이하 "서비스")의 이용 조건을 규정합니다.' },
      { t: 'h2', text: '1. 서비스 소개' },
      { t: 'p', text: 'AI issue는 인공지능 관련 뉴스 및 신규 툴 정보를 자동으로 수집·요약하여 제공하는 큐레이션 서비스입니다. 별도의 회원가입 없이 이용할 수 있으며, 뉴스레터 구독을 통해 정기적으로 정보를 받아볼 수 있습니다.' },
      { t: 'h2', text: '2. 콘텐츠 면책 조항' },
      { t: 'p', text: '서비스에서 제공하는 콘텐츠는 AI가 외부 RSS 피드 및 공개된 정보 소스를 자동 수집·요약한 것입니다.' },
      { t: 'ul', items: ['콘텐츠의 정확성, 완전성, 최신성을 보장하지 않습니다.', '서비스 운영자는 콘텐츠 이용으로 인해 발생한 손해에 대해 책임을 지지 않습니다.', '중요한 의사결정에는 원문 출처를 직접 확인하시기 바랍니다.'] },
      { t: 'h2', text: '3. 저작권' },
      { t: 'ul', items: ['서비스 자체 디자인, UI, 로고 등의 저작권은 AI issue에 있습니다.', '수집·요약된 콘텐츠의 저작권은 각 원문 출처에 있으며, 서비스는 해당 출처를 명시합니다.', '서비스 내 콘텐츠를 무단으로 복제·배포하는 행위를 금지합니다.'] },
      { t: 'h2', text: '4. 금지 행위' },
      { t: 'p', text: '이용자는 다음 행위를 해서는 안 됩니다.' },
      { t: 'ul', items: ['서비스를 불법적인 목적으로 이용하는 행위', '서비스의 정상적인 운영을 방해하는 행위', '타인의 개인정보를 수집하거나 도용하는 행위', '서비스 콘텐츠를 상업적으로 무단 이용하는 행위'] },
      { t: 'h2', text: '5. 서비스 변경 및 중단' },
      { t: 'p', text: '서비스는 운영상 필요에 따라 내용을 변경하거나 일시적으로 중단할 수 있습니다. 이로 인한 이용자의 손해에 대해 별도의 보상을 제공하지 않습니다.' },
      { t: 'h2', text: '6. 약관 변경' },
      { t: 'p', text: '본 약관은 서비스 정책 변경 시 수정될 수 있으며, 변경 시 서비스 내 공지를 통해 안내합니다. 변경된 약관은 공지 후 7일이 지난 시점부터 효력이 발생합니다.' },
      { t: 'h2', text: '7. 준거법 및 분쟁 해결' },
      { t: 'p', text: '본 약관의 해석 및 적용은 서비스 운영자의 소재지 법률을 준거법으로 하며, 이용자가 소재한 국가의 강행법규가 있는 경우 해당 법규가 우선 적용될 수 있습니다. 분쟁 발생 시 상호 협의를 통해 해결하는 것을 원칙으로 합니다.' },
      { t: 'h2', text: '8. 문의' },
      { t: 'ul', items: ['서비스명: AI issue', '이메일: contact@ai-issue.com'] },
    ],
  },
  en: {
    title: 'Terms of Service',
    effectiveDate: 'Effective Date: June 14, 2026',
    blocks: [
      { t: 'p', text: 'These Terms of Service govern your use of AI issue (the "Service").' },
      { t: 'h2', text: '1. About the Service' },
      { t: 'p', text: 'AI issue is a curation service that automatically collects and summarizes news and information about artificial intelligence tools. The Service is available without registration. You may also subscribe to our newsletter to receive regular updates.' },
      { t: 'h2', text: '2. Content Disclaimer' },
      { t: 'p', text: 'All content provided through the Service is automatically collected and summarized by AI from external RSS feeds and publicly available sources.' },
      { t: 'ul', items: ['We do not guarantee the accuracy, completeness, or timeliness of any content.', 'The Service operator is not liable for any damages arising from your use of the content.', 'For important decisions, please refer directly to the original sources.'] },
      { t: 'h2', text: '3. Intellectual Property' },
      { t: 'ul', items: ['The design, UI, logo, and other original elements of the Service are the property of AI issue.', 'The copyright of collected and summarized content belongs to the respective original sources, which the Service credits accordingly.', 'Unauthorized reproduction or distribution of content from the Service is prohibited.'] },
      { t: 'h2', text: '4. Prohibited Conduct' },
      { t: 'p', text: 'You agree not to:' },
      { t: 'ul', items: ['Use the Service for any unlawful purpose', 'Interfere with or disrupt the normal operation of the Service', 'Collect or misuse the personal information of others', 'Use Service content for commercial purposes without authorization'] },
      { t: 'h2', text: '5. Changes and Interruptions' },
      { t: 'p', text: 'The Service may modify its content or temporarily suspend operations as needed. We are not obligated to provide compensation for any resulting inconvenience or loss.' },
      { t: 'h2', text: '6. Changes to These Terms' },
      { t: 'p', text: 'These Terms may be updated from time to time. We will notify users of any material changes through the Service. Updated Terms will take effect 7 days after the notice is posted.' },
      { t: 'h2', text: '7. Governing Law and Dispute Resolution' },
      { t: 'p', text: 'These Terms are governed by the laws of the jurisdiction where the Service operator is located. Where mandatory local laws apply in your country of residence, such laws shall take precedence. We encourage resolving any disputes through good-faith negotiation before pursuing formal proceedings.' },
      { t: 'h2', text: '8. Contact' },
      { t: 'ul', items: ['Service: AI issue', 'Email: contact@ai-issue.com'] },
    ],
  },
};
